### ISSUE TITLE
Waiting For VS 2022

### ISSUE THREAD

**Issue by nirzaf** [tabnine/tabnine-visual-studio#5]
Thank you so much for expanding your services to Visual Studio, we are eagerly waiting for Visual Studio 2022 Version since it's almost production ready

**Comment by anton-martynyuk** [comment]
Can you please make it for VS 2022 ? We use this Studio for .NET 6

**Comment by shaigeva** [comment]
@anton-martynyuk thank you for the feedback!
It's being considered, but we don't have a timeline yet. We'll ping back here when we know more.

**Comment by jiayuehua** [comment]
I also really hope have it available for vs2022. We use it for C++.

**Comment by anton-martyniuk** [comment]
Any updates on when Tabnine will be available for VS 2022 ?

**Comment by nirzaf** [comment]
> Any updates on when Tabnine will be available for VS 2022 ?

Don’t worry they will release once Visual Studio 2024 released

**Comment by xMANIGHTx** [comment]
I would like to add myself to the choir. From .NET 6 onward we have to code with vs2022. Please don't let us down

**Comment by damien-c-d** [comment]
Our team of 30 Devs has been looking into AI Assistants for our projects. The lack of support for Visual Studio 2022 has ultimately lead us to go with an alternative solution as .NET 6 is the latest LTS version of .NET and requires Visual Studio 2022. Pricing would not have been an issue.

**Comment by hswami** [comment]
Same here for our team of 20-30 devs.

**Comment by nirzaf** [comment]
Stop wasting time here folks. Github Copilot is raising the dust. Just move ahead

**Comment by damien-c-d** [comment]
That's a pretty piss poor response. Do better.

**Comment by damien-c-d** [comment]
Yep that's what we went with. It's pretty piss poor that they haven't ported it to VS2022 considering many other extensions were within a week of GA. They need to do better.
