### ISSUE TITLE
Tabnine didn't start working automatically

### ISSUE THREAD

**Issue by maya-tabnine** [tabnine/tabnine-visual-studio#6]
In some cases, Tabnine suggestions are not showing right after the installation.
In order to get Tabnine to work in Visual Studio after the installation, you need to create a text file in your project and type tabnine::config in.

**Comment by Intecpsp** [comment]
Mine wasn't showing immediately after installing, but it felt like it had to "learn" my coding style before I got any recommendations.

**Comment by mhtvsSFrpHdE** [comment]
If your TabNine host application take too long (> 100 ms for whatever reason) to return suggestion to your IDE,  
the extension can refuse the result and show "No suggestion".

It's possible to fix it before an official update: https://github.com/tabnine/tabnine-visual-studio/issues/7#issuecomment-1261411286
