### ISSUE TITLE
vs2019 no options available

### ISSUE THREAD

**Issue by LaraSQP** [tabnine/tabnine-visual-studio#8]
There are no options available in vs2019.

This means that telemetry (and whatever else) might be mandatory.

Uninstalling.

**Comment by Intecpsp** [comment]
I hate to be "that guy", but did you search before opening a new issue? https://github.com/tabnine/tabnine-visual-studio/issues/4#issuecomment-956154594

**Comment by LaraSQP** [comment]
That's quite obscure.

Thank you, though.
