### ISSUE TITLE
Resharper support

### ISSUE THREAD

**Issue by hernan-torrez** [tabnine/tabnine-visual-studio#9]
Whenever Resharper is installed, Tabnine doesn't work in C# files, as Resharper takes over the standard mechanisms.

**Comment by shaigeva** [comment]
Thank you for reporting!
We are aware of this problem, and we're actively developing a separate Resharper plugin that will work when the Visual Studio plugin does not.

**Comment by anton-martyniuk** [comment]
Any updates on when new Tabnine plugin will be available for VS 2022 with Resharper enabled ?

**Comment by yonidavidson** [comment]
Hi @anton-martyniuk , the newest version 1.0.6 that is out in the marketplace will work also with Resharper.
